class ContentIndustryModel {
  int _id;
  String _typeName;
  int _parentId;
  String _createdTime;
  String _updatedTime;
  

  ContentIndustryModel(
      {int id,
        String typeName,
        int parentId,
        String createdTime,
        String updatedTime}) {
    this._id = id;
    this._typeName = typeName;
    this._parentId = parentId;
    this._createdTime = createdTime;
    this._updatedTime = updatedTime;
  }

  int get id => _id;
  set id(int id) => _id = id;
  String get typeName => _typeName;
  set typeName(String typeName) => _typeName = typeName;
  int get parentId => _parentId;
  set parentId(int parentId) => _parentId = parentId;
  String get createdTime => _createdTime;
  set createdTime(String createdTime) => _createdTime = createdTime;
  String get updatedTime => _updatedTime;
  set updatedTime(String updatedTime) => _updatedTime = updatedTime;

  ContentIndustryModel.fromJson(Map<String, dynamic> json) {
    _id = json['id'];
    _typeName = json['typeName'];
    _parentId = json['parentId'];
    _createdTime = json['createdTime'];
    _updatedTime = json['updatedTime'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this._id;
    data['typeName'] = this._typeName;
    data['parentId'] = this._parentId;
    data['createdTime'] = this._createdTime;
    data['updatedTime'] = this._updatedTime;
    return data;
  }
}
class Autogenerated {
  int _id;
  String _typeName;
  int _parentId;
  String _createdTime;
  String _updatedTime;

  Autogenerated(
      {int id,
        String typeName,
        int parentId,
        String createdTime,
        String updatedTime}) {
    this._id = id;
    this._typeName = typeName;
    this._parentId = parentId;
    this._createdTime = createdTime;
    this._updatedTime = updatedTime;
  }

  int get id => _id;
  set id(int id) => _id = id;
  String get typeName => _typeName;
  set typeName(String typeName) => _typeName = typeName;
  int get parentId => _parentId;
  set parentId(int parentId) => _parentId = parentId;
  String get createdTime => _createdTime;
  set createdTime(String createdTime) => _createdTime = createdTime;
  String get updatedTime => _updatedTime;
  set updatedTime(String updatedTime) => _updatedTime = updatedTime;

  Autogenerated.fromJson(Map<String, dynamic> json) {
    _id = json['id'];
    _typeName = json['typeName'];
    _parentId = json['parentId'];
    _createdTime = json['createdTime'];
    _updatedTime = json['updatedTime'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this._id;
    data['typeName'] = this._typeName;
    data['parentId'] = this._parentId;
    data['createdTime'] = this._createdTime;
    data['updatedTime'] = this._updatedTime;
    return data;
  }
}

